name: studentconnect
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/onboard.png
  - assets/logobk.png
  - assets/gm.png
  - assets/main.jpeg
  - assets/4.png
  - assets/7.png
  - assets/8.png
  - assets/1.png
  - assets/ghbasket.png
  - assets/jiji.jpg
  - assets/ovegh.png
  - assets/tonaton.png
  - assets/Group 3102.png
  - assets/map.jpg



